[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "celebrity-faces"
version = "0.1.0"
description = "Robust image classification under limited data"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
    { name = "babaksoft", email = "babak.eslamieh@gmail.com" },
]
keywords = ["machine learning", "classification"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license-files = ["LICEN[CS]E*"]

dependencies = [
    "tensorflow[and-cuda]",
    "torch",
    "torchvision",
    "pytorch-lightning",
    "matplotlib",
    "mlflow",
    "dvc[s3]",
]

[project.optional-dependencies]
dev = [
    "black",
    "ruff",
    "mypy",
    "isort",
    "pytest",
]

build = [
    "build",
    "hatchling",
]

[project.urls]
Homepage = "https://github.com/babaksoft/celebrity-faces"
Issues = "https://github.com/babaksoft/celebrity-faces/issues"

[tool.black]
target-version = ["py312"]

[tool.isort]
profile = "black"

[tool.hatch.build.targets.wheel]
packages = ["src/celebrity_faces"]

[tool.hatch.build]
exclude = [
    "/.dvc",
    "**/*.dvc",
    "**/.gitignore",
    "/notebooks",
    "/tests",
    ".gitignore",
    ".dvcignore",
    "requirements.txt"
]
